ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
