ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/codecs
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/isps
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/pproc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/jpeg_10

obj-$(CONFIG_MSMB_CAMERA) += msm.o
obj-$(CONFIG_MSMB_CAMERA) += camera/
obj-$(CONFIG_MSMB_CAMERA) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA) += sensor/
obj-$(CONFIG_MSMB_CAMERA) += pproc/
obj-$(CONFIG_MSMB_CAMERA) += isp/
obj-$(CONFIG_MSMB_CAMERA) += ispif/
obj-$(CONFIG_MSMB_JPEG) += jpeg_10/
obj-$(CONFIG_MSMB_CAMERA) += msm_buf_mgr/
