ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
