ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gucci/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
